### ISSUE TITLE
Type error while formatting

### ISSUE THREAD

**Issue by Hwan-seok** [zeroturnaround/sql-formatter#129]
## Wanna format
```
CREATE TABLE IF NOT EXISTS `user_associated_capsule` (`user_uid` VARCHAR(255) , `capsule_uid` CHAR(36) BINARY , `did_open_request` TINYINT(1) DEFAULT false, `is_opened` TINYINT(1) DEFAULT false, PRIMARY KEY (`user_uid`, `capsule_uid`), FOREIGN KEY (`user_uid`) REFERENCES `user` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`capsule_uid`) REFERENCES `capsule` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
```

## Expected result
```
CREATE TABLE IF NOT EXISTS `user_associated_capsule` (
    `user_uid` VARCHAR(255),
    `capsule_uid` CHAR(36)BINARY,
    `did_open_request` TINYINT(1) DEFAULT FALSE,
    `is_opened` TINYINT(1) DEFAULT FALSE,
    PRIMARY KEY (`user_uid` , `capsule_uid`),
    FOREIGN KEY (`user_uid`)
        REFERENCES `user` (`uid`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`capsule_uid`)
        REFERENCES `capsule` (`uid`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;
```

## Actual 
```
TypeError: Cannot read property 'slice' of undefined at parseKey(\sql-formatter\lib\core\Tokenizer.js:191:20)
 at Tokenizer.getPlaceholderTokenWithKey(\sql-formatter\lib\core\Tokenizer.js:235:21)
...

```

#### Dialect
- mysql

**Comment by psacawa** [comment]
I encounter this with a simpler case:

*command.sql*

```
SeleCt * from mytable where true  and false ;
```

When running `cat command.sql | sql-formatter`, I get:

```
/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:191
          return v.slice(1);
                   ^

TypeError: Cannot read property 'slice' of undefined
    at parseKey (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:191:20)
    at Tokenizer.getPlaceholderTokenWithKey (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:235:21)
    at Tokenizer.getIdentNamedPlaceholderToken (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:187:19)
    at Tokenizer.getPlaceholderToken (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:182:19)
    at Tokenizer.getNextToken (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:127:147)
    at Tokenizer.tokenize (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Tokenizer.js:107:24)
    at StandardSqlFormatter.format (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/core/Formatter.js:87:38)
    at format (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/lib/sqlFormatter.js:74:29)
    at Object.<anonymous> (/home/psacawa/.nvm/versions/node/v14.15.0/lib/node_modules/sql-formatter/bin/sqlfmt.js:102:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

Yet it works if I run instead `sql-formatter -l postgresql`.

**Comment by eyalroth** [comment]
Same here with this case:
```js
const sqlFormatter = require('sql-formatter');
sqlFormatter.format(`SELECT CASE (1=1) WHEN true THEN 'true' WHEN false THEN 'false' END`);
```
Looks like literal booleans are the problem.

Setting the language to `postgresql` as suggested by @psacawa works, but this should work with to dialects as well.

**Comment by xixixao** [comment]
Minimal repro: `SELECT * FROM foo WHERE false` blows up, `SELECT * FROM foo WHERE true` works.

**Comment by nene** [comment]
Fixed in latest master.
