### ISSUE TITLE
Feature request: Support for delimiter

### ISSUE THREAD

**Issue by duongthienlee** [zeroturnaround/sql-formatter#184]
Hi, thank you for creating such a great library.
It would be great if there is an option that we can specify the delimiter so that the formatter can ignore formatting it.
With current formatter, with the following sql text

    DELIMITER //
    
    CREATE FUNCTION FortyTwo() RETURNS TINYINT DETERMINISTIC
    BEGIN
      DECLARE x TINYINT;
      SET x = 42;
      RETURN x;
    END 
    //
    
    DELIMITER ; 

It returns this
    
    DELIMITER / /
    CREATE
       FUNCTION FortyTwo() RETURNS TINYINT DETERMINISTIC
    BEGIN
       DECLARE x TINYINT;
    
    SET x = 42;
    
    RETURN x;
    
    END / / DELIMITER;

**Comment by nene** [comment]
Currently the only option on table is to don't touch the formatting of anything between `DELIMITER //` and `DELIMITER ;`.

Though really even this is not near the list of features considered for now.

But I'll leave this issue open to see how much interest there even is in such a feature.

**Comment by mattsbennett** [comment]
I could really use this as well.

**Comment by grantwforsythe** [comment]
Bumping because I would also really appreciate this feature

**Comment by zinw** [comment]
+1

**Comment by carywreams** [comment]
would also appreciate this. -- started using CTEs to eliminate duplicated code in stored procedures. want to use sql-formatter at the end of the build process to format the final stored proc. 

## my work-around

+ use ``$$`` instead of ``//`` as a delimiter to eliminate the space introduced which produces ``/ /``. 
+ use sed to clean up the final END sequence:

```
/opt/node-v16.15.0-linux-x64/bin/sql-formatter -c sql-formatter.json |\
 sed 's/\sdelimiter.*/\ndelimiter ;/g'  
```

**Comment by karlhorky** [comment]
To be clear, the `$$` delimiter also currently causes `sql-formatter` to crash.

Eg. the following PostgreSQL function example code from [the PostgreSQL docs](https://www.postgresql.org/docs/current/sql-createfunction.html#:~:text=Increment%20an%20integer%2C%20making%20use%20of%20an%20argument%20name%2C%20in%20PL/pgSQL%3A):

```sql
CREATE OR REPLACE FUNCTION increment(i integer) RETURNS integer AS $$
        BEGIN
                RETURN i + 1;
        END;
$$ LANGUAGE plpgsql;
```

Causes the following crash:

```
Error: Parse error: Unexpected "$$
       " at line 4 column 10
    at TokenizerEngine.createParseError (file:///Users/k/p/project/node_modules/sql-formatter/lib/lexer/TokenizerEngine.js:53:12)
    at TokenizerEngine.tokenize (file:///Users/k/p/project/node_modules/sql-formatter/lib/lexer/TokenizerEngine.js:35:22)
    at Tokenizer.tokenize (file:///Users/k/p/project/node_modules/sql-formatter/lib/lexer/Tokenizer.js:16:47)
    at LexerAdapter.tokenize (file:///Users/k/p/project/node_modules/sql-formatter/lib/parser/createParser.js:16:76)
    at LexerAdapter.reset (file:///Users/k/p/project/node_modules/sql-formatter/lib/parser/LexerAdapter.js:17:24)
    at Parser.feed (/Users/k/p/project/node_modules/nearley/lib/nearley.js:281:15)
    at Object.parse (file:///Users/k/p/project/node_modules/sql-formatter/lib/parser/createParser.js:26:18)
    at Formatter.parse (file:///Users/k/p/project/node_modules/sql-formatter/lib/formatter/Formatter.js:32:49)
    at Formatter.format (file:///Users/k/p/project/node_modules/sql-formatter/lib/formatter/Formatter.js:25:22)
    at formatDialect (file:///Users/k/p/project/node_modules/sql-formatter/lib/sqlFormatter.js:78:57)
```

**Comment by karlhorky** [comment]
Would be great to have support for formatting PL/pgSQL in `$$` delimiters, eg. the following PostgreSQL function example code from [the PostgreSQL docs](https://www.postgresql.org/docs/current/sql-createfunction.html#:~:text=Increment%20an%20integer%2C%20making%20use%20of%20an%20argument%20name%2C%20in%20PL/pgSQL%3A):

```sql
CREATE OR REPLACE FUNCTION increment(i integer) RETURNS integer AS $$
        BEGIN
                RETURN i + 1;
        END;
$$ LANGUAGE plpgsql;
```

**Comment by nene** [comment]
@karlhorky the $$ delimited strings in postgres are supported. You just need to specify postgresql as the language to be formatted. See the FAQ.

**Comment by karlhorky** [comment]
Oh I meant the PL/pgSQL inside of the `$$` - but I guess this is involved, because it's a different language.

```sql
CREATE OR REPLACE FUNCTION increment(i integer) RETURNS integer AS $$
                  BEGIN
         RETURN i + 1;
        END;
$$ LANGUAGE plpgsql;
```

Formatted:

```sql
CREATE
OR REPLACE FUNCTION increment (i integer) RETURNS integer AS $$
                  BEGIN
         RETURN i + 1;
        END;
$$ LANGUAGE plpgsql;
```

Expected:

```sql
CREATE
OR REPLACE FUNCTION increment (i integer) RETURNS integer AS $$
  BEGIN
    RETURN i + 1;
  END;
$$ LANGUAGE plpgsql;
```

**Comment by karlhorky** [comment]
Separate feature request for formatting SQL in SQL here:

- #680

**Comment by theking2** [comment]
> would also appreciate this. -- started using CTEs to eliminate duplicated code in stored procedures. want to use sql-formatter at the end of the build process to format the final stored proc.
> ## my work-around
> 
>     * use `$$` instead of `//` as a delimiter to eliminate the space introduced which produces `/ /`.
> 
>     * use sed to clean up the final END sequence:
> 
> 
> ```
> /opt/node-v16.15.0-linux-x64/bin/sql-formatter -c sql-formatter.json |\
>  sed 's/\sdelimiter.*/\ndelimiter ;/g'  
> ```

No it doesn't. It gives an error on $$

**Comment by karlhorky** [comment]
> No it doesn't. It gives a parse error on `$$`

@theking2 can you provide a demo where this is failing? It's working with latest `sql-formatter` version for our projects. You need to make sure to specify the `postgresql` language, as @nene mentioned in [his comment](https://github.com/sql-formatter-org/sql-formatter/issues/184#issuecomment-1828033318) above

> the $$ delimited strings in postgres are supported. You just need to specify postgresql as the language to be formatted. See the FAQ.

**Comment by nene** [comment]
Well, I for one would be surprised if it does work.

I suspect @karlhorky is talking about `$$`-delimited strings in Postgres, not about changing statement delimiter from `;` to something else (which this issue is really about).

**Comment by theking2** [comment]
Is there a setting like `"sql-formatter.dialect"` which could be set to mariadb/mysql?

**Comment by nene** [comment]
See the readme: https://github.com/sql-formatter-org/sql-formatter#configuration-options

**Comment by theking2** [comment]
> See the readme: https://github.com/sql-formatter-org/sql-formatter#configuration-options

Ok. but it seems not to include the DELIMITER syntax

**Comment by nene** [comment]
That's right. There is no support for DELIMITER. Which is also pretty clearly stated in README.

**Comment by theking2** [comment]
and that is going to change sometime?

**Comment by nene** [comment]
Unlikely. Though I'm open to pull requests if anybody wishes to tackle this problem. But as you can see, this issue was opened in 2021.

Also, I'm personally not planning any real feature development on this library. Instead concentrating on developing `prettier-plugin-sql-cst`, which for now also doesn't support delimiter changing. Though I'm more likely to implement such feature there rather than here.

**Comment by kingma-sbw** [comment]
> Show off-topic message

```sql
DROP Procedure IF EXISTS `Test`;

DELIMITER $$
CREATE /* DEFINER=`zeugnis_nm_dev`@`localhost` */ PROCEDURE `Test`()
    NO SQL
Select 1$$
DELIMITER ;
```
becomes

```sql
DROP Procedure
  IF EXISTS `Test`;


DELIMITER $$ CREATE
/* DEFINER=`zeugnis_nm_dev`@`localhost` */
PROCEDURE `Test`() NO SQL
Select
  1 $$ DELIMITER;
```

**Comment by carywreams** [comment]
@theking2 ,

my workaround isn't working **any more** for me. I'm now stuck on sql-formatter pulling the create statement up to the same line as the delimiter declaration -- a seemingly new behavior with my change to v15.0.2 ( I had been using something with node v16).  I'll see what I can do, as I'll be actively working to get sql-formatter back into my workflow.

**Comment by nene** [comment]
I implemented [a new feature](https://github.com/sql-formatter-org/sql-formatter#disabling-the-formatter) that allows for a cleaner work-around for issues like this.

In short, you can wrap the problematic SQL between special comments that turn off the formatter:

```sql
/* sql-formatter-disable */
DELIMITER //

CREATE FUNCTION FortyTwo() RETURNS TINYINT DETERMINISTIC
BEGIN
  DECLARE x TINYINT;
  SET x = 42;
  RETURN x;
END 
//

DELIMITER ; 
/* sql-formatter-enable */
```

**Comment by kingma-sbw** [comment]
Could this be written thusly?:
```sql
/* sql-formatter-disable */
DELIMITER //
/* sql-formatter-enable */
CREATE FUNCTION FortyTwo() RETURNS TINYINT DETERMINISTIC
BEGIN
  DECLARE x TINYINT;
  SET x = 42;
  RETURN x;
END 
//
/* sql-formatter-disable */
DELIMITER ; 
/* sql-formatter-enable */
```

The `CREATE FUNCTION` is "normal" SQL.

**Comment by nene** [comment]
Sure. You can try it on the [demo page](https://sql-formatter-org.github.io/sql-formatter/). But SQL Formatter does not handle procedural SQL well.

**Comment by theking2** [comment]
> Show off-topic message
> > No it doesn't. It gives a parse error on `$$`
> 
> @theking2 can you provide a demo where this is failing? It's working with latest `sql-formatter` version for our projects.
> 
> One note: you need to make sure to specify the `postgresql` language, as @nene mentioned in [his comment](https://github.com/sql-formatter-org/sql-formatter/issues/184#issuecomment-1828033318) above
> 
> > the $$ delimited strings in postgres are supported. You just need to specify postgresql as the language to be formatted. See the FAQ.

I cannot use postgressql at it fails on this:
![image](https://github.com/user-attachments/assets/33dcddd5-cf51-4249-af4b-46e77ffb424e)


Unable to format SQL:
Error: Parse error: Unexpected "`post_proc" at line 1 column 26.
SQL dialect used: "postgresql".

**Comment by kingma-sbw** [comment]
I found a workarout using:
 `DELIMITER #`

This is a valid (comment) token and gets overwriten as delimiter.
